### ISSUE TITLE
Clean up Websockets Logic

### ISSUE THREAD

**Issue by davidmkershaw** [citrusbyte/oncilla#43]
Realize this probably isn't directly related to this PR but it's kind of weird here how `authDetails` is a Promise and `details` is the actual details. This could be cleaned up by
1) defining `authDetails` like this:
```typescript
let authDetails: AuthDetails | undefined = undefined;
```
2) writing `handlers.auth` as `async`:
```typescript
auth: async msg => {
  const { token } = msg;
  if (!auth) throw new Error("Unexpected auth message");
  authDetails = await auth
    .parseToken(token, {
      close: () => socket.terminate()
    })
    .catch(() => undefined);
  processCache();
},
```
3) For `handlers.push()`, remove the `async` and change the `if` block:
```typescript
  if (auth) {
    if (!authDetails) {
      addToQueue(msg);
      return;
    }
    if (!auth.canWrite({ auth: authDetails, kind, id })) return;
  }
```
4) also do the same with the function that's passed as the last parameter to `getAndObserve()` in `handlers.subscribe()`:
```typescript
v => {
  if (auth) {
    if (!authDetails) {
```

_Originally posted by @nateq314 in https://github.com/citrusbyte/oncilla/pull/40_

**Comment by denis-sokolov** [comment]
As suggested, this would be a change in behavior. The authDetails promise has hidden another queue. I have clarified our auth queues in #44.
