### ISSUE TITLE
Revise Footer and License

### ISSUE THREAD

**Issue by aarongreenlee** [citrusbyte/oncilla#64]
* Please add a LICENSE.md file which includes the same content currently linked on Facebook's React repo
* Please update the GitHub repository to reflect the MIT license in metadata which should result in MIT being reflected in the license portion of the GitHub UI
* Please add the following to the footer of the README.md (please find a Theorem logo we can host and replace the Citrusbyte one I've linked):

```
## About Theorem

![Theorem](http://i.imgur.com/W6eISI3.png)

This software is lovingly maintained and funded by Theorem.
From whiteboarding new concepts to long-term support, Theorem works with startups and large multi-national enterprises to develop new applications, software, services, and platforms to achieve the best results and deliver Full Stack Innovation™

At Theorem we believe in and support open-source software.

* Check out more of our open-source software at Theorem.
* Learn more about [our work](https://theorem.co/portfolio).
* [Hire us](https://theorem.co/contact) to work on your project.
* [Want to join the team?](https://theorem.co/careers)

*Theorem and the Theorem logo are trademarks or registered trademarks of Theorem, LLC.*
```

**Comment by denis-sokolov** [comment]
All fixed now, including the license detection:
![image](https://user-images.githubusercontent.com/113721/61549533-f1acfa00-aa58-11e9-8764-96a7ab254bf4.png)

And including the logo:
![image](https://user-images.githubusercontent.com/113721/61549578-09847e00-aa59-11e9-97d5-4812fc9fa610.png)


If you want to continue thinking about ISC vs MIT, feel free to re-open.
